### ISSUE TITLE
Orthopter SF with missing ReferenceType

### ISSUE THREAD

**Issue by mdoering** [Sp2000/colplus-repo#33]
The verbatim ACEF data for 1021 has no reference type for ref links and therefore the refs are not linked anywhere:

https://www.col.plus/dataset/1021/verbatim?type=acef:CommonNames&type=acef:NameReferencesLinks&acef:ReferenceID=12244&acef:ReferenceID=12244&termOp=OR

Column ReferenceType in NameReferences.txt is always empty

**Comment by mdoering** [comment]
See also https://www.col.plus/dataset/1021/issues
We should keep an eye on the red import issues

**Comment by mdoering** [comment]
also a lot of non unique ids which is likely serious

**Comment by gdower** [comment]
@mdoering, I took a look at the original data and Species Files Group doesn't specify the reference type. I'll check with Marilyn to see if they have that data available. ITIS also has 3,436 scientific_name_references without a reference type.

**Comment by gdower** [comment]
Based on talking with Marilyn, I think maybe reference type should be optional because the reference type isn't always specified by specialists, although Species File Group might be able to provide that info in the next update. Alternatively, she suggested setting them to taxonomic references.

For the ThripsWiki web crawler, I designated the reference type as nomenclatural if the scientific name author string matched the reference author string, and taxonomic otherwise. Some of those references could probably be both nomenclatural and taxonomic though.

I'm looking into the other issue with the non-unique IDs.

**Comment by mdoering** [comment]
I will then default all ACEF references to taxonomic ones if not given
