### ISSUE TITLE
Convert legacy workbench SQL into decisions

### ISSUE THREAD

**Issue by gdower** [Sp2000/colplus-repo#74]
The legacy workbench has SQL code that was used to apply decisions mostly to the automated pipelines from WoRMS, Paris, Species Files, etc., but also World Plants and it could potentially be a large amount of work to manually re-enter those past decisions. I'll investigate whether it is feasible to convert the SQL code into CoL+ decisions.

**Comment by gdower** [comment]
Some of the legacy SQL decisions are likely obsolete, in which case they should show up in the [API](http://api.col.plus/decision/broken) so I won't worry about trying to detect obsolete decisions.

**Comment by gdower** [comment]
There's around 2000 lines of legacy decisions for WoRMs. The legacy code is frequently stuff like this:

```SQL
UPDATE scientific_names SET sp2000_status_id=4 WHERE name_code IN ('W-Amp-754201','W-Amp-754210');

UPDATE scientific_names SET sp2000_status_id=2 WHERE name_code IN ('W-Amp-492058', 'W-Amp-492075', 'W-Amp-488451', 'W-Amp-823725', 'W-Amp-509498', 'W-Amp-509506', 'W-Amp-745776', 'W-Amp-759362', 'W-Amp-102429', 'W-Amp-102430', 'W-Amp-493282', 'W-Amp-493274', 'W-Amp-526394', 'W-Amp-102596', 'W-Amp-526222', 'W-Amp-526221', 'W-Amp-531701', 'W-Amp-531371', 'W-Amp-557372', 'W-Amp-557363', 'W-Amp-556112', 'W-Amp-556106', 'W-Amp-103234', 'W-Amp-557764') AND sp2000_status_id=5;
```

Using the set `W-Amp-754201` from above as an example, I could translate that decision to:

```JSON
POST //decision
{
  "subjectDatasetKey": "1202",
  "subject": {
    "id": "754210"
  },
  "mode": "update",
  "status": "provisionally accepted"
}
```

The frontend sets more complex decisions that include the scientific name, authorship, and rank, which I assume is used to only apply the decision only if there's an exact match:

```JSON
{
  "subjectDatasetKey": "1202",
  "subject": {
    "id": "754210",
    "name": "Idunella nana",
    "authorship": "(Krapp-Schickel, 1975)",
    "rank": "species"
  },
  "mode": "update",
  "status": "provisionally accepted"
}
```

It would add an extra step, but I could write a script to also query the [verbatim data](https://api.col.plus/dataset/1202/verbatim?q=754210&type=acef%3AAcceptedSpecies&type=acef%3AAcceptedInfraSpecies) to get the scientific names and authorship, which would probably be a good idea to safeguard against decisions being incorrectly applied if for some reason the IDs ever changed. I prefer that approach.

**Comment by mdoering** [comment]
@gdower good idea to translate these into decisions as much as possible. 

In general decisions (as well as sectors or species estimates) need to have an ID that can be joined in the respective dataset, otherwise they show up as broken decisions and cannot be applied. The name, authorship, rank, status, et al. is used to a) to rematch a decision when it is broken or the dataset is updated/reimported as we cannot trust ids to be stable across versions and b) have some human context. If feasable it would therefore be really good to include at least name, authorship and rank. In case we deal with duplicates the status and parent could also be relevant to be sure we match the right record from a duplicates pair. I guess this is impossible to know from looking at the sql, so we should just stick with the minimum above.

The fake decision threw a 400 because the datasetKey did not exist. The ID is not checked on purpose. But if obsolete these should show up as broken decisions which we then can remove.

@gdower how do you plan to store these decisions? We are still wiping for a few weeks, so we need to be able to replay them.

**Comment by mdoering** [comment]
I would probably wait with the name and classification update decisions.
Status updates make sense. Hopefully these are the majority

**Comment by gdower** [comment]
@mdoering, I'll translate the decisions into a spreadsheet and generate the the decisions JSON from that. Then I'll just post the decisions to the API when we go into production. Similarly, I think we could also start getting decisions ready for the datasets that we have in queue so that we can catch up quickly in the 2nd monthly. For that we'd apply the decisions on dev and then just copy the decisions JSON filtered by datasetKey and re-post the decisions in the 2nd monthly.

**Comment by mdoering** [comment]
if thats not too much of a trouble this sounds fine!

**Comment by mdoering** [comment]
we can also get them in via a sql script if you prefer that

**Comment by mdoering** [comment]
The decisions file is still empty, but it would go here:
https://github.com/Sp2000/colplus-backend/blob/master/colplus-dao/src/main/resources/org/col/db/decisions.sql

Similar to the sectors we create here, e.g. for World Plants:
https://github.com/Sp2000/colplus-backend/blob/master/colplus-dao/src/main/resources/org/col/db/sectors-old.sql#L26

**Comment by gdower** [comment]
That might be easier. I'll look into doing it that way.

**Comment by mdoering** [comment]
for all columns see: https://github.com/Sp2000/colplus-backend/blob/master/colplus-dao/src/main/resources/org/col/db/dbschema.sql#L279
