### ISSUE TITLE
Update GSD metadata

### ISSUE THREAD

**Issue by gdower** [Sp2000/colplus-repo#77]
It would be better to wait until the infrastructure is in production before editing the metadata so that it is not wiped out.

**Comment by mdoering** [comment]
... unless you want to put it into the archives SourceDatabase file

**Comment by mdoering** [comment]
Prod is ready to be updated.
Be aware though that GSD metadata is updated from the archives if any metadata is found in them

**Comment by yroskov** [comment]
Missing metadata (**Geographic scope; Checklist Confidence; Completeness**) are fixed in Clearinghouse for 16 GSDs, 2020-01-02:   
CCW 100%  5* 
ETI WBD (Euphausiacea) 99% 5*
Glomeromycota 100% 5*
MOST 95% 4*
TicksBase 98% 5*
UCD 95% 4*
LDL Neuropterida 99% 5*
OlogamasidBase 99% 5*
Taxapad Ichneumonoidea 97% 5*
RhodacaridBase 99% 5*
PhytoseiidBase 99% 5*
TenuipalpidBase 99% 5*
Systema Dipterorum 98% 4*
WoRMS Trematoda 33% 4*
FADA Halacaridae 25% 4*
WoRMS Ostracoda 49% 4*
